# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: front-end footpath
description: # this means to ignore newlines until "baseurl:"
  morsels of code + jolts of JS
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thmsdnnr.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  thmsdnnr
twitter_username: thmsdnnr
social:
  name: Thomas Danner
  links:
    - https://www.codewars.com/users/thmsdnnr
    - https://github.com/thmsdnnr
    - https://codepen.io/thmsdnnr/
    - https://www.freecodecamp.org/thmsdnnr
    - https://twitter.com/thmsdnnr
    - https://www.facebook.com/thmsdnnr
# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

  # Assets Pipeline
assets:
  sources:
    - _assets
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
